In [21]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [22]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/YapayZekaOdevleri/weather_data.csv')

In [24]:
df

Gün Hava Durumu Sıcaklık     Nem   Yağış Oyun
0    G1     Güneşli    Sıcak  Yüksek  Seyrek  Yok
1    G2     Güneşli    Sıcak  Yüksek   Aşırı  Yok
2    G3      Kapalı    Sıcak  Yüksek  Seyrek  Var
3    G4    Yağmurlu   Ilıman  Yüksek  Seyrek  Var
4    G5    Yağmurlu    Soğuk  Normal  Seyrek  Var
5    G6    Yağmurlu    Soğuk  Normal   Aşırı  Yok
6    G7      Kapalı    Soğuk  Normal   Aşırı  Var
7    G8     Güneşli   Ilıman  Yüksek  Seyrek  Var
8    G9     Güneşli    Soğuk  Normal  Seyrek  Yok
9   G10    Yağmurlu   Ilıman  Normal  Seyrek  Var
10  G11     Güneşli   Ilıman  Normal   Aşırı  Var
11  G12      Kapalı   Ilıman  Yüksek   Aşırı  Yok
12  G13      Kapalı    Sıcak  Normal  Seyrek  Var
13  G14    Yağmurlu   Ilıman  Yüksek   Aşırı  Yok

In [25]:
df.drop(columns =['Sıcaklık','Nem'])

Gün Hava Durumu   Yağış Oyun
0    G1     Güneşli  Seyrek  Yok
1    G2     Güneşli   Aşırı  Yok
2    G3      Kapalı  Seyrek  Var
3    G4    Yağmurlu  Seyrek  Var
4    G5    Yağmurlu  Seyrek  Var
5    G6    Yağmurlu   Aşırı  Yok
6    G7      Kapalı   Aşırı  Var
7    G8     Güneşli  Seyrek  Var
8    G9     Güneşli  Seyrek  Yok
9   G10    Yağmurlu  Seyrek  Var
10  G11     Güneşli   Aşırı  Var
11  G12      Kapalı   Aşırı  Yok
12  G13      Kapalı  Seyrek  Var
13  G14    Yağmurlu   Aşırı  Yok

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Gün          14 non-null     object
 1   Hava Durumu  14 non-null     object
 2   Sıcaklık     14 non-null     object
 3   Nem          14 non-null     object
 4   Yağış        14 non-null     object
 5   Oyun         14 non-null     object
dtypes: object(6)
memory usage: 800.0+ bytes


In [27]:
df.describe()

Gün Hava Durumu Sıcaklık     Nem   Yağış Oyun
count   14          14       14      14      14   14
unique  14           3        3       2       2    2
top     G1     Güneşli   Ilıman  Yüksek  Seyrek  Var
freq     1           5        6       7       8    8

In [30]:
myArray = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [31]:
myArray.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [33]:
random = np.random.randint(1,100,3)

In [36]:
random.reshape(3,1)

array([[49],
       [53],
       [14]])

In [37]:
random

array([49, 53, 14])